name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-24.04-arm
    container: swift:latest
    steps:
    - uses: actions/checkout@v4
    - run: whereis swift
    - run : apt install curl
    - run: curl https://dl.google.com/android/repository/android-ndk-r27c-linux.zip
    - run: ls -a
