name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-24.04-arm
    container: swift:latest
    steps:
    - uses: actions/checkout@v4
    - uses: android-actions/setup-android@v3
    - run: sdkmanager "ndk;27.2.12479018"
    - run: echo "NDK path: $ANDROID_SDK_ROOT/ndk/27.2.12479018"
    - run: whereis swift
    - run: ls -a
