name: Release

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  build-android:
    runs-on: ubuntu-latest
    container: registry.gitlab.com/finestructure/spi-images:android-6.1-latest
    steps:
      - uses: actions/checkout@v4
      - run: swiftc -swift-version 6 -O hello.swift -o hello-android
      - run: tar -zcvf hello-android.tar.gz hello-android
      - uses: actions/upload-artifact@v4
        with:
          name: hello-android
          path: hello-android.tar.gz

  build-linux:
    runs-on: ubuntu-latest
    container: swift:latest
    steps:
      - uses: actions/checkout@v4
      - run: swiftc -swift-version 6 -O hello.swift -o hello-linux
      - run: tar -zcvf hello-linux.tar.gz hello-linux
      - uses: actions/upload-artifact@v4
        with:
          name: hello-linux
          path: hello-linux.tar.gz

  build-macos:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - run: sudo xcode-select --switch /Applications/Xcode_16.4.app
      - run: swiftc -swift-version 6 -O hello.swift -o hello-macos
      - run: tar -zcvf hello-macos.tar.gz hello-macos
      - uses: actions/upload-artifact@v4
        with:
          name: hello-macos
          path: hello-macos.tar.gz

  release:
    needs: [build-android, build-linux, build-macos]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: ./artifacts
      - name: Extract all files
        run: |
          cd artifacts
          find ./ -maxdepth 3
          for dir in */ ; do
            echo $dir
          done
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/**/hello-*
