name: CI

on: push

jobs:
  release:
    runs-on: ubuntu-24.04-arm
    steps:
    - uses: actions/checkout@v4
    - uses: android-actions/setup-android@v3
    - run: sdkmanager "ndk;27.2.12479018"
    - run: echo $ANDROID_SDK_ROOT
    - run: whereis swift
    - run: ls -a
