name: CI

on: push

jobs:
  build-android:
    runs-on: ubuntu-latest
    container: registry.gitlab.com/finestructure/spi-images:android-6.1-latest
    steps:
    - uses: actions/checkout@v4
    - run: swift --version
    - run: swiftc -sdk aarch64-unknown-linux-android24 -target aarch64-unknown-linux-android24 -o hello.swift hello
    - run: ./hello
  build-linux:
    runs-on: ubuntu-latest
    container: swift:latest
    steps:
      - uses: actions/checkout@v4
      - run: swiftc -swift-version 6 -O hello.swift -o hello
      - run: ./hello
  build-macos:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - run: sudo xcode-select --switch /Applications/Xcode_16.4.app
      - run: swiftc -swift-version 6 -O hello.swift -o hello
      - run: ./hello
