name: CI

on: push

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: nttld/setup-ndk@v1
      id: setup-ndk
      with:
        ndk-version: r26d
    - run: ls -la ${{ steps.setup-ndk.outputs.ndk-path }}
    - run: apt-get update && apt-get install tar
    - run: curl -O https://download.swift.org/swiftly/linux/swiftly-$(uname -m).tar.gz && \
            tar zxf swiftly-$(uname -m).tar.gz && \
            ./swiftly init --quiet-shell-followup && \
            . "${SWIFTLY_HOME_DIR:-~/.local/share/swiftly}/env.sh" && \
            hash -r
    - run: swift --version
